spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  redis:
    hostname:
    port:
    username:
    password:
  rabbitmq:
    addresses:
    queue: ms.orders
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8081/admin-console
        auto-deregistration: true
        username: admin
        password: password
        instance:
          service-base-url: http://localhost:8080
          metadata:
            user:
              name: admin
              password: password
  application:
    name: orders-api

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html


