spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  rabbitmq:
    addresses: amqps://***
    queue: ms.orders
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8081/admin-console
        auto-deregistration: true
  application:
    name: ms-order

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html


