server:
  port: 8081
  servlet:
    context-path: /admin-console

spring:
  security:
    user:
      name: admin
      password: password
  boot:
    admin:
      client:
        username: admin
        password: password
        instance:
          metadata:
            user:
              name: client
              password: password